### PR TITLE
Main Class created, Login class created.

### PR DESCRIPTION
**Pull request by akash-d-dev**
- Class created
- This pointer used

### CODE REVIEW

**Comment by Tharun-kailash** [comment]
Thanks for submitting, Akash.
Whenever you raise the PR, post the video link here. Pl do this now.

**Comment by akash-d-dev** [comment]
> Thanks for submitting, Akash. Whenever you raise the PR, post the video link here. Pl do this now.

Sorry for the delay, Tharun. I missed the notification, but I had already posted the video and PR link in the Kalvium community submission.

https://drive.google.com/file/d/1IhcCgpOtpDZQKWkMFHAKA9zNdEEV65kA/view?usp=sharing

**Comment by Tharun-kailash** [comment]
I have reviewed your PR and  video.
You have explained the classes and how you created the basic UI using swings in java which is clear. However you didn't explain the instantiation. Do this in your next PR!

You can go ahead and merge this PR!
Thanks.

**Comment by akash-d-dev** [comment]
> instantiation

https://drive.google.com/drive/folders/1Qf2rS_WIetn2Pj4ZbDAvOC8PynKdkIZx?usp=sharing

I have added another explanation video which containes the missing explanation.

**Comment by Tharun-kailash** [comment]
Hey Akash, I have reviewed the video.
Will update the scores in livebooks.
Proceed with further concepts.

**Review by th3c0d3br34ker — COMMENTED** [review]
Submission was missing for `this` pointer. Submitted during viva and marks were updated.

**Pull request merged**
